services:
  - type: web
    name: webhooktest-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: REDIS_URL
        fromService:
          type: redis
          name: webhooktest-redis
          property: connectionString
      - key: CORS_ORIGIN
        value: https://webhooktest.dev,https://www.webhooktest.dev

databases:
  - name: webhooktest-redis
    databaseName: webhooktest
    user: webhooktest